"""empty message

Revision ID: 4b538bea030f
Revises: 512bb2389097
Create Date: 2016-08-16 11:37:19.035416

"""

# revision identifiers, used by Alembic.
revision = '4b538bea030f'
down_revision = '512bb2389097'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oral', sa.Column('department', sa.Enum('Art', 'Dance', 'Music', 'Theatre', 'Anthropology', 'Economics', 'History', 'Political Science', 'Sociology', 'American Studies', 'Chinese', 'Classics', 'English', 'Creative Writing', 'French', 'General LIterature', 'German', 'Russian', 'Spanish', 'Biology', 'Chemistry', 'Mathematics', 'Physics', 'Linguistics', 'Philosophy', 'Psychology', 'Religion', name='department'), nullable=True))
    op.add_column('oral', sa.Column('division', sa.Enum('The Arts', 'History and Social Sciences', 'Literature and Languages', 'Mathematics and Natural Sciences', 'Philosophy, Religion, Psychology, and Linguistics', name='division'), nullable=True))
    op.drop_column('stu', 'department')
    op.drop_column('stu', 'division')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stu', sa.Column('division', postgresql.ENUM('The Arts', 'History and Social Sciences', 'Literature and Languages', 'Mathematics and Natural Sciences', 'Philosophy, Religion, Psychology and Linguistics', name='division'), autoincrement=False, nullable=True))
    op.add_column('stu', sa.Column('department', postgresql.ENUM('Anthropology', 'Art', 'Biology', 'Chemistry', 'Chinese', 'Classics', 'Dance', 'Economics', 'English', 'French', 'German', 'History', 'Linguistics', 'Mathematics', 'Music', 'Philosophy', 'Physics', 'Political Science', 'Psychology', 'Religion', 'Russian', 'Sociology', 'Spanish', 'Theatre', name='department'), autoincrement=False, nullable=True))
    op.drop_column('oral', 'division')
    op.drop_column('oral', 'department')
    ### end Alembic commands ###
