"""empty message

Revision ID: 512bb2389097
Revises: None
Create Date: 2016-08-01 10:31:51.355538

"""

# revision identifiers, used by Alembic.
revision = '512bb2389097'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oral_start_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('start', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('dtstart', sa.DateTime(), nullable=False),
    sa.Column('dtend', sa.DateTime(), nullable=False),
    sa.Column('private', sa.Boolean(), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.CheckConstraint('dtstart <= dtend'),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prof',
    sa.Column('department', sa.Enum('Anthropology', 'Art', 'Biology', 'Chemistry', 'Chinese', 'Classics', 'Dance', 'Economics', 'English', 'French', 'German', 'History', 'Linguistics', 'Mathematics', 'Music', 'Philosophy', 'Physics', 'Political Science', 'Psychology', 'Religion', 'Russian', 'Sociology', 'Spanish', 'Theatre', name='department'), nullable=True),
    sa.Column('division', sa.Enum('The Arts', 'History and Social Sciences', 'Literature and Languages', 'Mathematics and Natural Sciences', 'Philosophy, Religion, Psychology and Linguistics', name='division'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stu',
    sa.Column('department', sa.Enum('Anthropology', 'Art', 'Biology', 'Chemistry', 'Chinese', 'Classics', 'Dance', 'Economics', 'English', 'French', 'German', 'History', 'Linguistics', 'Mathematics', 'Music', 'Philosophy', 'Physics', 'Political Science', 'Psychology', 'Religion', 'Russian', 'Sociology', 'Spanish', 'Theatre', name='department'), nullable=True),
    sa.Column('division', sa.Enum('The Arts', 'History and Social Sciences', 'Literature and Languages', 'Mathematics and Natural Sciences', 'Philosophy, Religion, Psychology and Linguistics', name='division'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stu_id', sa.Integer(), nullable=True),
    sa.Column('response', sa.Enum('Accepted', 'Declined', 'Tentative', name='response'), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['stu_id'], ['stu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('readers',
    sa.Column('prof_id', sa.Integer(), nullable=True),
    sa.Column('oral_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['oral_id'], ['oral.id'], ),
    sa.ForeignKeyConstraint(['prof_id'], ['prof.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('readers')
    op.drop_table('oral')
    op.drop_table('stu')
    op.drop_table('prof')
    op.drop_table('event')
    op.drop_table('user')
    op.drop_table('oral_start_day')
    ### end Alembic commands ###
